# Redmi A2 BoardConfig.mk
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_VARIANT := cortex-a53

TARGET_BOOTLOADER_BOARD_NAME := MT6765
TARGET_KERNEL_USE := 4.19
TARGET_DEVICE_DIR := device/xiaomi/RedmiA2

BOARD_BOOTIMAGE_PARTITION_SIZE := 0x4000000
BOARD_SUPERIMAGE_PARTITION_SIZE := 0xe0000000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0xc0000000
BOARD_VBMETAIMAGE_PARTITION_SIZE := 0x800000
BOARD_FLASH_BLOCK_SIZE := 0x20000

BOARD_HAS_NO_REAL_SDCARD := true
BOARD_RECOVERY_SWIPE := true
BOARD_USES_RECOVERY_AS_BOOT := false
